package udev

import (
	"fmt"
	"regexp"
	"strings"
	"time"
)

// PermissionMode is either GroupPlugdev or Mode0666.
type PermissionMode int

const (
	GroupPlugdev PermissionMode = iota
	Mode0666
)

// Options configures rule generation.
type Options struct {
	IncludeHidraw   bool // add hidraw rules for raw HID (Wine/Proton)
	TagAsJoystick   bool // set ENV{ID_INPUT_JOYSTICK}="1" so SDL/Proton treats device as joystick (helps rudder pedals)
	Permission      PermissionMode
}

// DeviceID is vendor:product (lowercase, 4-char each).
type DeviceID struct {
	Vendor  string
	Product string
}

func (d DeviceID) String() string {
	return fmt.Sprintf("%s:%s", d.Vendor, d.Product)
}

// NormalizeVIDPID returns 4-char lowercase hex for use in rules.
func NormalizeVIDPID(vendor, product string) (v, p string) {
	v = strings.TrimSpace(strings.ToLower(vendor))
	p = strings.TrimSpace(strings.ToLower(product))
	for _, s := range []*string{&v, &p} {
		if strings.HasPrefix(*s, "0x") {
			*s = (*s)[2:]
		}
		for len(*s) < 4 {
			*s = "0" + *s
		}
		if len(*s) > 4 {
			*s = (*s)[len(*s)-4:]
		}
	}
	return v, p
}

// Generate produces udev rule lines for the given device IDs.
func Generate(ids []DeviceID, opts Options) string {
	var b strings.Builder
	b.WriteString("# Generated by goudev\n")
	b.WriteString(fmt.Sprintf("# %s\n", time.Now().Format(time.RFC3339)))
	perm := "MODE=\"0660\", GROUP=\"plugdev\""
	if opts.Permission == Mode0666 {
		perm = "MODE=\"0666\""
	}

	joystickTag := ""
	if opts.TagAsJoystick {
		joystickTag = ", ENV{ID_INPUT_JOYSTICK}=\"1\""
	}
	for _, id := range ids {
		// Input (evdev) - required for X-Plane and most games
		line := fmt.Sprintf("KERNEL==\"event*\", SUBSYSTEM==\"input\", ATTRS{idVendor}==\"%s\", ATTRS{idProduct}==\"%s\", %s%s\n",
			id.Vendor, id.Product, perm, joystickTag)
		b.WriteString(line)
		if opts.IncludeHidraw {
			lineHid := fmt.Sprintf("KERNEL==\"hidraw*\", SUBSYSTEM==\"hidraw\", ATTRS{idVendor}==\"%s\", ATTRS{idProduct}==\"%s\", %s\n",
				id.Vendor, id.Product, perm)
			b.WriteString(lineHid)
		}
	}
	return strings.TrimSuffix(b.String(), "\n")
}

// RulesFileName is the udev rules file we manage.
const RulesFileName = "85-goudev.rules"

// RulesDir is the standard udev rules directory.
const RulesDir = "/etc/udev/rules.d"

// FullPath returns the path to our rules file.
func FullPath() string {
	return RulesDir + "/" + RulesFileName
}

// ruleLineRegex matches a line we generate (with optional ENV{ID_INPUT_JOYSTICK}="1" at end).
var ruleLineRegex = regexp.MustCompile(`^KERNEL=="(event\*|hidraw\*)", SUBSYSTEM=="(input|hidraw)", ATTRS\{idVendor\}=="[0-9a-f]{4}", ATTRS\{idProduct\}=="[0-9a-f]{4}", (MODE="0666"|MODE="0660", GROUP="plugdev")(, ENV\{ID_INPUT_JOYSTICK\}="1")?$`)

// ValidateRules checks that the rule content is well-formed and safe to install.
// Comment lines and empty lines are ignored.
func ValidateRules(content string) error {
	lines := strings.Split(content, "\n")
	for i, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if !ruleLineRegex.MatchString(line) {
			return fmt.Errorf("invalid rule at line %d: %q", i+1, line)
		}
	}
	return nil
}
