package udev

import (
	"fmt"
	"regexp"
	"strings"
	"time"
	"unicode"
)

// PermissionMode is either GroupPlugdev or Mode0666.
type PermissionMode int

const (
	GroupPlugdev PermissionMode = iota
	Mode0666
)

// Options configures rule generation.
type Options struct {
	IncludeHidraw bool // add hidraw rules for raw HID (Wine/Proton)
	TagAsJoystick bool // set ENV{ID_INPUT_JOYSTICK}="1" so SDL/Proton treats device as joystick (helps rudder pedals)
	Permission    PermissionMode
}

// DeviceID is vendor:product (lowercase, 4-char each).
type DeviceID struct {
	Vendor  string
	Product string
}

func (d DeviceID) String() string {
	return fmt.Sprintf("%s:%s", d.Vendor, d.Product)
}

// NormalizeVIDPID returns 4-char lowercase hex for use in rules.
func NormalizeVIDPID(vendor, product string) (v, p string) {
	v = strings.TrimSpace(strings.ToLower(vendor))
	p = strings.TrimSpace(strings.ToLower(product))
	for _, s := range []*string{&v, &p} {
		if strings.HasPrefix(*s, "0x") {
			*s = (*s)[2:]
		}
		for len(*s) < 4 {
			*s = "0" + *s
		}
		if len(*s) > 4 {
			*s = (*s)[len(*s)-4:]
		}
	}
	return v, p
}

// Generate produces udev rule lines for the given device IDs.
func Generate(ids []DeviceID, opts Options) string {
	var b strings.Builder
	b.WriteString("# Generated by goudev\n")
	b.WriteString(fmt.Sprintf("# %s\n", time.Now().Format(time.RFC3339)))
	perm := "MODE=\"0660\", GROUP=\"plugdev\""
	if opts.Permission == Mode0666 {
		perm = "MODE=\"0666\""
	}

	joystickTag := ""
	if opts.TagAsJoystick {
		joystickTag = ", ENV{ID_INPUT_JOYSTICK}=\"1\""
	}
	for _, id := range ids {
		// Input (evdev) - required for X-Plane and most games
		line := fmt.Sprintf("KERNEL==\"event*\", SUBSYSTEM==\"input\", ATTRS{idVendor}==\"%s\", ATTRS{idProduct}==\"%s\", %s%s\n",
			id.Vendor, id.Product, perm, joystickTag)
		b.WriteString(line)
		if opts.IncludeHidraw {
			lineHid := fmt.Sprintf("KERNEL==\"hidraw*\", SUBSYSTEM==\"hidraw\", ATTRS{idVendor}==\"%s\", ATTRS{idProduct}==\"%s\", %s\n",
				id.Vendor, id.Product, perm)
			b.WriteString(lineHid)
		}
	}
	return strings.TrimSuffix(b.String(), "\n")
}

const rulesFilePrefix = "85-"
const rulesFileSuffix = ".rules"

// RulesDir is the standard udev rules directory.
const RulesDir = "/etc/udev/rules.d"

// RulesFileName returns a readable per-device udev rules filename.
func RulesFileName(names []string, ids []DeviceID) string {
	slug := slugFromNames(names)
	if slug == "" {
		slug = slugFromIDs(ids)
	}
	if slug == "" {
		slug = "device"
	}
	return rulesFilePrefix + slug + rulesFileSuffix
}

// FullPath returns the path to the provided rules file.
func FullPath(fileName string) string {
	return RulesDir + "/" + fileName
}

func slugFromNames(names []string) string {
	var slugs []string
	for _, name := range names {
		slug := slugify(name)
		if slug == "" {
			continue
		}
		if len(slugs) > 0 && slug == slugs[len(slugs)-1] {
			continue
		}
		slugs = append(slugs, slug)
		if len(slugs) == 2 {
			break
		}
	}
	switch len(slugs) {
	case 0:
		return ""
	case 1:
		return slugs[0]
	default:
		return slugs[0] + "-plus-" + fmt.Sprintf("%d", len(names)-1)
	}
}

func slugFromIDs(ids []DeviceID) string {
	if len(ids) == 0 {
		return ""
	}
	if len(ids) == 1 {
		return "device-" + ids[0].Vendor + "-" + ids[0].Product
	}
	return "devices-" + ids[0].Vendor + "-" + ids[0].Product + "-plus-" + fmt.Sprintf("%d", len(ids)-1)
}

func slugify(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	if s == "" {
		return ""
	}
	var b strings.Builder
	lastDash := false
	for _, r := range s {
		switch {
		case unicode.IsLetter(r) || unicode.IsDigit(r):
			b.WriteRune(r)
			lastDash = false
		case !lastDash:
			b.WriteByte('-')
			lastDash = true
		}
	}
	slug := strings.Trim(b.String(), "-")
	if len(slug) > 40 {
		slug = strings.Trim(slug[:40], "-")
	}
	return slug
}

// ruleLineRegex matches a line we generate (with optional ENV{ID_INPUT_JOYSTICK}="1" at end).
var ruleLineRegex = regexp.MustCompile(`^KERNEL=="(event\*|hidraw\*)", SUBSYSTEM=="(input|hidraw)", ATTRS\{idVendor\}=="[0-9a-f]{4}", ATTRS\{idProduct\}=="[0-9a-f]{4}", (MODE="0666"|MODE="0660", GROUP="plugdev")(, ENV\{ID_INPUT_JOYSTICK\}="1")?$`)

// ValidateRules checks that the rule content is well-formed and safe to install.
// Comment lines and empty lines are ignored.
func ValidateRules(content string) error {
	lines := strings.Split(content, "\n")
	for i, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if !ruleLineRegex.MatchString(line) {
			return fmt.Errorf("invalid rule at line %d: %q", i+1, line)
		}
	}
	return nil
}
